#!/bin/bash

run() {
  ./run $1 true
}

./reset
users="alice bob charlie"

docker build -t rcs/gpg .
for user in $users $users
do
  run $user
done

echo -e "\n\nInitialized. Execute ./run {user} to step into a shell."
